export const TOPICS_OF_INTEREST = [
  { value: "building-feminist-economies", label: "Building feminist economies" },
  { value: "storytelling-for-impact", label: "Storytelling for impact" },
  { value: "leadership-development", label: "Leadership development" },
  { value: "innovation-technology", label: "Innovation & technology" },
  { value: "social-entrepreneurship", label: "Social entrepreneurship" },
  { value: "gender-equality", label: "Gender equality" },
  { value: "climate-action", label: "Climate action" },
  { value: "financial-inclusion", label: "Financial inclusion" },
  { value: "education-empowerment", label: "Education & empowerment" },
  { value: "health-wellness", label: "Health & wellness" },
  { value: "policy-advocacy", label: "Policy & advocacy" },
  { value: "community-building", label: "Community building" },
  { value: "digital-transformation", label: "Digital transformation" },
  { value: "sustainable-development", label: "Sustainable development" },
  { value: "mentorship-coaching", label: "Mentorship & coaching" },
  { value: "networking-partnerships", label: "Networking & partnerships" },
  { value: "research-data", label: "Research & data" },
  { value: "arts-culture", label: "Arts & culture" },
  { value: "media-communications", label: "Media & communications" },
  { value: "human-rights", label: "Human rights" },
]

export const AREAS_OF_EXPERTISE = [
  { value: "executive-leadership", label: "Executive leadership" },
  { value: "entrepreneurship", label: "Entrepreneurship" },
  { value: "finance-investment", label: "Finance & investment" },
  { value: "technology-engineering", label: "Technology & engineering" },
  { value: "marketing-communications", label: "Marketing & communications" },
  { value: "human-resources", label: "Human resources" },
  { value: "operations-management", label: "Operations management" },
  { value: "strategy-consulting", label: "Strategy & consulting" },
  { value: "product-management", label: "Product management" },
  { value: "sales-business-development", label: "Sales & business development" },
  { value: "legal-compliance", label: "Legal & compliance" },
  { value: "research-development", label: "Research & development" },
  { value: "education-training", label: "Education & training" },
  { value: "healthcare-medicine", label: "Healthcare & medicine" },
  { value: "nonprofit-social-impact", label: "Nonprofit & social impact" },
  { value: "government-public-policy", label: "Government & public policy" },
  { value: "media-journalism", label: "Media & journalism" },
  { value: "design-creative", label: "Design & creative" },
  { value: "data-analytics", label: "Data & analytics" },
  { value: "sustainability-environment", label: "Sustainability & environment" },
  { value: "international-development", label: "International development" },
  { value: "venture-capital", label: "Venture capital" },
  { value: "board-governance", label: "Board & governance" },
  { value: "diversity-inclusion", label: "Diversity & inclusion" },
  { value: "supply-chain", label: "Supply chain" },
  { value: "cybersecurity", label: "Cybersecurity" },
  { value: "artificial-intelligence", label: "Artificial intelligence" },
  { value: "blockchain-crypto", label: "Blockchain & crypto" },
  { value: "biotechnology", label: "Biotechnology" },
  { value: "renewable-energy", label: "Renewable energy" },
]